PKG_NAME = zeromq
PKG_VERS = 4.0.5
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://download.zeromq.org
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = http://zeromq.org/
COMMENT  = 
LICENSE  =

GNU_CONFIGURE = 1
CONFIGURE_ARGS = --without-documentation
 
include ../../mk/spksrc.cross-cc.mk


